const R = React;
const NS = 'EfolusiDesignSystem_4ffc3d';
let regCache = null;
function loadRegistry() {
  if (!regCache) regCache = fetch('./registry.js').then(r => r.text()).then(t => {
    const i = t.indexOf('GROUPS = ');
    return JSON.parse(t.slice(i + 9, t.lastIndexOf(';')));
  }).catch(() => []);
  return regCache;
}
// Pages and docs come from site/nav.json (generated by scripts/build_site_nav.mjs
// from the actual site/*.dc.html files), so a new page shows up here without
// editing any array in this file.
let navCache = null;
function loadNav() {
  if (!navCache) navCache = fetch('./nav.json').then(r => r.json()).catch(() => ({ pages: [], docs: [] }));
  return navCache;
}
function SiteSearch() {
  const [open, setOpen] = R.useState(false);
  const [groups, setGroups] = R.useState(null);
  R.useEffect(() => {
    const onKey = e => {
      if ((e.metaKey || e.ctrlKey) && String(e.key).toLowerCase() === 'k') { e.preventDefault(); setOpen(o => !o); }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, []);
  R.useEffect(() => {
    if (!open || groups) return;
    Promise.all([loadRegistry(), loadNav()]).then(([gs, nav]) => {
      const comps = [];
      (gs || []).forEach(g => (g.items || []).forEach(it => comps.push({ id: './Components.dc.html#' + g.id + '/' + it.name, label: it.name, hint: g.label })));
      setGroups([
        { group: 'Pages', items: (nav.pages || []).map(p => ({ id: p.id, label: p.label, icon: p.icon })) },
        { group: 'Docs', items: (nav.docs || []).map(d => ({ id: d.id, label: d.label, icon: 'book-open' })) },
        { group: 'Components', items: comps },
      ]);
    });
  }, [open, groups]);
  const ds = window[NS] || {};
  const CP = ds.CommandPalette;
  const Icon = ds.Icon;
  return R.createElement('span', null,
    R.createElement('button', {
      onClick: () => setOpen(true), 'aria-label': 'Search documentation', className: 'site-search',
      style: { display: 'flex', alignItems: 'center', gap: 8, height: 36, padding: '0 8px 0 10px', border: '1px solid var(--border-default)', borderRadius: 'var(--radius-sm)', background: 'var(--surface-card)', color: 'var(--text-muted)', fontFamily: 'var(--font-sans)', fontSize: 13, cursor: 'pointer', flex: 'none', justifyContent: 'flex-start' },
    },
      Icon ? R.createElement(Icon, { name: 'search', size: 14 }) : null,
      R.createElement('span', { className: 'site-search-label', style: { flex: 1, textAlign: 'left', whiteSpace: 'nowrap', overflow: 'hidden' } }, 'Search docs…'),
      R.createElement('span', { className: 'site-search-kbd', style: { fontFamily: 'var(--font-mono)', fontSize: 11, border: '1px solid var(--border-default)', borderRadius: 4, padding: '1px 5px', background: 'var(--surface-page)' } }, '⌘K')
    ),
    CP && groups ? R.createElement(CP, {
      open, onClose: () => setOpen(false), groups,
      placeholder: 'Search components, docs, pages…',
      onSelect: id => { setOpen(false); location.href = id; },
    }) : null
  );
}
module.exports = { SiteSearch };
