// Build @efolusi/meridian-icons into packages/icons/dist/.
//
// The 108 Lucide-derived icons as a standalone package, for anyone who wants the
// raw SVGs without the React components: the SVG files themselves (for design
// tools and build pipelines), plus a JS index mapping name -> svg string (for
// programmatic use). Assembled from the same assets/icons/ the umbrella inlines,
// so the sets cannot drift.
//
//   node scripts/build_pkg_icons.mjs          # write packages/icons/dist/
//   node scripts/build_pkg_icons.mjs --check  # verify dist/ matches the sources
//
// Version is read from _ds_manifest.json, the single source the whole repo bumps.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ICON_DIR = path.join(ROOT, 'assets', 'icons');
const OUT = path.join(ROOT, 'packages', 'icons', 'dist');
const CHECK = process.argv.includes('--check');
const version = JSON.parse(fs.readFileSync(path.join(ROOT, '_ds_manifest.json'), 'utf8')).version;

const names = fs.readdirSync(ICON_DIR).filter(f => f.endsWith('.svg')).map(f => f.replace(/\.svg$/, '')).sort();

const files = new Map(); // package-relative path -> string

// The raw SVGs, kept under svg/ so `@efolusi/meridian-icons/svg/check.svg` works.
for (const name of names) {
  files.set(`svg/${name}.svg`, fs.readFileSync(path.join(ICON_DIR, `${name}.svg`), 'utf8'));
}

// The programmatic index: name -> svg source. Sorted, so the output is stable.
const map = names
  .map(n => `  ${JSON.stringify(n)}: ${JSON.stringify(files.get(`svg/${n}.svg`).trim())},`)
  .join('\n');
files.set('index.js',
  `// Generated by scripts/build_pkg_icons.mjs from assets/icons/. Do not edit.\n` +
  `export const icons = {\n${map}\n};\n` +
  `export const iconNames = Object.keys(icons);\n` +
  `export function getIcon(name) { return icons[name]; }\n`);
files.set('index.d.ts',
  `/** Every icon's raw SVG source, keyed by name. */\n` +
  `export declare const icons: Record<string, string>;\n` +
  `/** Every icon name. */\n` +
  `export declare const iconNames: string[];\n` +
  `/** The raw SVG for a name, or undefined. */\n` +
  `export declare function getIcon(name: string): string | undefined;\n`);

// Lucide licence travels with the icons it covers.
files.set('LICENSE-Lucide.txt', fs.readFileSync(path.join(ICON_DIR, 'LICENSE-Lucide.txt'), 'utf8'));

files.set('package.json', JSON.stringify({
  name: '@efolusi/meridian-icons',
  version,
  description: `The ${names.length} Lucide-derived icons of @efolusi/meridian, standalone: raw SVGs plus a name-to-svg index. Framework-agnostic.`,
  license: 'MIT',
  homepage: 'https://meridian.efolusi.com',
  repository: { type: 'git', url: 'git+https://github.com/efolusi/meridian.git', directory: 'packages/icons' },
  type: 'module',
  main: './index.js',
  types: './index.d.ts',
  exports: {
    '.': { types: './index.d.ts', default: './index.js' },
    './svg/*': './svg/*',
    './package.json': './package.json',
  },
  keywords: ['icons', 'svg', 'lucide', 'meridian'],
}, null, 2) + '\n');

if (CHECK) {
  const stale = [];
  for (const [rel, content] of files) {
    const p = path.join(OUT, rel);
    if (!fs.existsSync(p) || fs.readFileSync(p, 'utf8') !== content) stale.push(rel);
  }
  if (stale.length) {
    console.error(`packages/icons/dist is out of date (${stale.length} file(s)), e.g. ${stale.slice(0, 3).join(', ')}`);
    console.error('run: node scripts/build_pkg_icons.mjs');
    process.exit(1);
  }
  console.log(`@efolusi/meridian-icons dist matches the sources (${files.size} files, ${names.length} icons)`);
  process.exit(0);
}

fs.rmSync(OUT, { recursive: true, force: true });
for (const [rel, content] of files) {
  const p = path.join(OUT, rel);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, content);
}
console.log(`@efolusi/meridian-icons@${version}: ${files.size} files (${names.length} icons) -> packages/icons/dist/`);
